server:
  port: 8090
  error:
    include-exception: true

register:
  host: localhost
  port: 9000

eureka:
  instance:
    hostname: localhost
    instance-id: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${register.host}:${register.port}/eureka/

spring:
  datasource:
    name: devutility-test-database-mybatis-springboot
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.31.139:3306/yibai_plan_warehousing?useUnicode=true&useSSL=false
      username: warehousing
      password: warehousing
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
  application:
    name: plan-warehousing
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  rabbitmq:
    host: 192.168.71.146
    port: 5672
    username: admin
    password: 123456

test:
  datasource:
    names: ds1,ds2,ds3
    ds1:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/yibai_plan_warehousing?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: zxf123
    ds2:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&useSSL=false
      username: root
      password: root
    ds3:
      driver: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.71.170/yibai_plan_stock?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: zhangxiaofei
      password: zhxf@39


mybatis:
  mapper-locations: classpath*:com/yibai/plan/warehousing/dao/mapping/*.xml
  type-aliases-package: com.yibai.plan.warehousing.dao.entity

feign:
  hystrix:
    enabled: false

snowflake:
  worker: 0
  datacenter: 1


